apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tic-tac-toe
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MIN2MAX-M/devsecops-demo
    targetRevision: main
    path: kubernetes/base/deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tic-tac-toe
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
